# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 08:25
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


def migrate_to_treenode(apps, schema_editor):
    Page = apps.get_model('cms', 'Page')
    PageNode = apps.get_model('cms', 'PageNode')
    db_alias = schema_editor.connection.alias
    nodes = PageNode.objects.using(db_alias)

    for node in nodes.select_related('page'):
        page = node.page
        page_ids = [page.pk]

        if page.publisher_public_id:
            page_ids.append(page.publisher_public_id)
        Page.objects.using(db_alias).filter(pk__in=page_ids).update(node=node)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_pages',
                                    to='cms.PageNode'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('node', 'publisher_is_draft')]),
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'permissions': (('view_page', 'Can view page'), ('publish_page', 'Can publish page'), ('edit_static_placeholder', 'Can edit static placeholders')), 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterModelManagers(
            name='pageusergroup',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pagenode',
            unique_together=set([]),
        ),
        migrations.RunPython(migrate_to_treenode),
        migrations.AlterField(
            model_name='page',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_pages',
                                    to='cms.PageNode'),
        ),
        migrations.AlterField(
            model_name='pagenode',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='djangocms_nodes',
                                    to='sites.Site', verbose_name='site'),
        ),
    ]
