# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pagenode',
            table='cms_treenode',
        ),
    ]
