# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 08:25
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
    ]

    operations = []
