# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20180115_0825'),
    ]

    operations = []
