# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20180115_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='site',
        ),
        migrations.RemoveField(
            model_name='page',
            name='revision_id',
        ),
        migrations.RemoveField(
            model_name='treenode',
            name='page',
        ),
    ]
